### ISSUE TITLE
Add ESLint

### ISSUE THREAD

**Issue by chadhietala** [sangm/ember-scoped-query-cache#2]
Noticed a couple Nits in #1 that would have been caught by the linter. Please add ESLint to this project so we can focus on what the code is doing.

**Comment by scalvert** [comment]
Agree. Why do addon blueprints not include this by default?

**Comment by chadhietala** [comment]
Ah it is in the project but maybe not all the rules are installed.

**Comment by scalvert** [comment]
It's setup already, but the default config was pretty simple. I've added a more robust config in #1
