### ISSUE TITLE
Why is `queryCache` "public"?

### ISSUE THREAD

**Issue by jtlan** [sangm/ember-scoped-query-cache#3]
It looks like the `queryCache` method is exposed and callable by outside code. It seems like outside code using the cache shouldn't be aware of its implementation or accessing underlying methods.

**Comment by scalvert** [comment]
If `queryCache` weren't public, how could you call `scheduleDecay` to schedule it? This should be handled by the Route, and triggered when appropriate. 

Think of this as an API that the Route controls.

Example:

```js
import Ember from 'ember';
import ScopedQueryCacheMixin from 'ember-scoped-query-cache/mixins/scoped-query-cache';

export default Ember.Route.extend({
  deactivate() {
    this.queryCache.scheduleDecay(10000);
  }
});
```

This puts the control of how to enable the cache decay in the hands of the implementor, and doesn't tie the behavior to deeply with the mixin. The mixin just provides the API; it's up to the engineer to make it functional.

If you have an alternate approach, please provide an example that illustrates the approach you'd like to propose we take.

**Comment by jtlan** [comment]
I meant [`queryCache()`](https://github.com/sangm/ember-scoped-query-cache/blob/master/addon/mixins/scoped-query-cache.js#L37) the method, and not the cache object itself. That part makes sense.

**Comment by sangm** [comment]
Are you saying it's "public" because it doesn't have underscores or some type of convention to indicate that it's private?

**Comment by scalvert** [comment]
That method has been renamed, and it's marked as private via `_`
